name: Update Servers

on:
  schedule:
    - cron: "*/10 * * * *"
  workflow_dispatch:

jobs:
  build_and_deploy:
    runs-on: [self-hosted, ubuntu-latest]
    steps:
      - uses: actions/checkout@v2
      - run: "./build.sh"
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: "${{ secrets.GITHUB_TOKEN }}"
          firebaseServiceAccount: "${{ secrets.FIREBASE_SERVICE_ACCOUNT_OPENPROXYPROJECT }}"
          channelId: live
          projectId: openproxyproject
